apiVersion: v1
kind: Pod # Type of Kubernetes object here is a Pod
metadata:
  name: nginx # Name of the Pod
spec:
  containers:
    - name: nginx # Name of the container
      image: nginx:alpine
      ports:
        - containerPort: 80
